baseURL = "https://mergewayhq.github.io/"
languageCode = "en-us"
title = "Mergeway"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
enableGitInfo = true

[module]
  proxy = "direct"
  [module.hugoVersion]
    extended = true
    min = "0.73.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/mergewayhq/mergeway-cli/docs"
    disable = false

    # Getting started
    [[module.imports.mounts]]
      source = "src/getting-started"
      target = "content/cli/getting-started"
      excludeFiles = ["README.md"]
    [[module.imports.mounts]]
      source = "src/getting-started/README.md"
      target = "content/cli/getting-started/_index.md"

    # Guides
    [[module.imports.mounts]]
      source = "src/guides"
      target = "content/cli/guides"
      excludeFiles = ["README.md"]
    [[module.imports.mounts]]
      source = "src/guides/README.md"
      target = "content/cli/guides/_index.md"

    # CLI reference
    [[module.imports.mounts]]
      source = "src/cli-reference"
      target = "content/cli/reference"
      excludeFiles = ["README.md"]
    [[module.imports.mounts]]
      source = "src/cli-reference/README.md"
      target = "content/cli/reference/_index.md"
    [[module.imports.mounts]]
      source = "src/cli-reference/assets/erd-example-full.png"
      target = "content/cli/reference/gen-erd/assets/erd-example-full.png"

    # Main README
    [[module.imports.mounts]]
      source = "src/README.md"
      target = "content/cli/_index.md"

#    [[module.imports.mounts]]
#      source = "src/cli-reference"
#      target = "content/cli/reference"
#      excludeFiles = ["README.md"]
#    [[module.imports.mounts]]
#      source = "src/cli-reference/README.md"
#      target = "content/cli/reference/_index.md"
#    [[module.imports.mounts]]
#      source = "src/README.md"
#      target = "content/cli/_index.md"
#    [[module.imports.mounts]]
#      source = "src/how-to"
#      target = "content/cli/guides"
#      excludeFiles = ["README.md"]
#    [[module.imports.mounts]]
#      source = "src/how-to/README.md"
#      target = "content/cli/guides/_index.md"
#    [[module.imports.mounts]]
#      source = "src/getting-started.md"
#      target = "content/cli/docs/getting-started.md"
#    [[module.imports.mounts]]
#      source = "src/installation.md"
#      target = "content/cli/docs/installation.md"
#    [[module.imports.mounts]]
#      source = "src/concepts.md"
#      target = "content/cli/docs/concepts.md"
#    [[module.imports.mounts]]
#      source = "src/schema-spec.md"
#      target = "content/cli/docs/schema-spec.md"
#    [[module.imports.mounts]]
#      source = "arch/storage-layout.md"
#      target = "content/cli/docs/arch/storage-layout.md"

[params]
  copyright = "Mergeway"
  privacy_policy = ""
  offlineSearch = true

[params.ui]
  sidebar_menu_compact = false
  sidebar_search_disable = false
  navbar_logo = true
  showLightDarkModeMenu = true

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Getting Started"
    url = "/cli/getting-started/"
    weight = 10
  [[menu.main]]
    name = "CLI Reference"
    url = "/cli/reference/"
    weight = 20
  [[menu.main]]
    name = "Guides"
    url = "/cli/guides/"
    weight = 30
#  [[menu.main]]
#    name = "Blog"
#    url = "/blog/"
#    weight = 40
